// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkNLpMfFI9UQqjwiShl3riFwxVzaGtXI',
    appId: '1:481439361547:web:aeb24ab62e8d5bd61d750e',
    messagingSenderId: '481439361547',
    projectId: 'lostandfound-aaada',
    authDomain: 'lostandfound-aaada.firebaseapp.com',
    storageBucket: 'lostandfound-aaada.firebasestorage.app',
    measurementId: 'G-10TLYPZEBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQn1rzLL8yCCwNV1EOCL9JbhE8hlj3XeU',
    appId: '1:481439361547:android:6a6c12f25ac6101f1d750e',
    messagingSenderId: '481439361547',
    projectId: 'lostandfound-aaada',
    storageBucket: 'lostandfound-aaada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU77BqlXUmLiSKlhz6wVU8E-lkdxukOz0',
    appId: '1:481439361547:ios:2ab85631753e359c1d750e',
    messagingSenderId: '481439361547',
    projectId: 'lostandfound-aaada',
    storageBucket: 'lostandfound-aaada.firebasestorage.app',
    iosBundleId: 'com.example.lostandfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU77BqlXUmLiSKlhz6wVU8E-lkdxukOz0',
    appId: '1:481439361547:ios:2ab85631753e359c1d750e',
    messagingSenderId: '481439361547',
    projectId: 'lostandfound-aaada',
    storageBucket: 'lostandfound-aaada.firebasestorage.app',
    iosBundleId: 'com.example.lostandfound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUkNLpMfFI9UQqjwiShl3riFwxVzaGtXI',
    appId: '1:481439361547:web:e9455971e3a51da41d750e',
    messagingSenderId: '481439361547',
    projectId: 'lostandfound-aaada',
    authDomain: 'lostandfound-aaada.firebaseapp.com',
    storageBucket: 'lostandfound-aaada.firebasestorage.app',
    measurementId: 'G-62EMYLQP4C',
  );
}
